---

# All the variables are present in var/var_alldetails.yml

- name: Create AWS EC2
  hosts: localhost
  connection: local
  vars_files:
  - var/var_alldetails

  tasks:
  - name: create VPC        # create VPC using cidr block
    ec2_vpc_net:
      name: "{{ vpc_name }}"
      cidr_block: "{{ vpc_cidr_block }}"
      region: "{{ aws_region }}"
      state: present
    register: ec2_vpc_net_out

  - name:               Set VPC ID in variable
    set_fact:
      vpc_id:           "{{ ec2_vpc_net_out.vpc.id }}"

#  - debug:
#      msg: vpc id  {{ ec2_vpc_net_out.vpc.id }}  vpc name {{ vpc_name }}

# Tow subnets shall be created.
# Two for AZ1, two for AZ2.
# For each AZ : one public, one private.

# Creating Subnets in AZ-1

  - name:               Create Public Subnet [AZ-1]
    ec2_vpc_subnet:
      state:            "present"
      vpc_id:           "{{ vpc_id }}"
      cidr:             "10.0.1.0/24"
      az:               "{{ aws_region }}a"
      region:           "{{ aws_region }}"
      resource_tags:
        Name:           "AZ-1 Public Subnet 1"
    register: my_public_subnet_az1

  - name:               Set Public Subnet ID in variable [AZ-1]
    set_fact:
      public_subnet_az1_id: "{{ my_public_subnet_az1.subnet.id }}"

#  - debug:
#      msg: public subnet "{{ my_public_subnet_az1.subnet.id }}"

  - name:               Create Private Subnet [AZ-1]
    ec2_vpc_subnet:
      state:            "present"
      vpc_id:           "{{ vpc_id }}"
      cidr:             "10.0.2.0/24"
      az:               "{{ aws_region }}a"
      region:           "{{ aws_region }}"
      resource_tags:
        Name:           "AZ-1 Private Subnet 1"
    register: my_private_subnet_az1

  - name:               Set Private Subnet ID in variable [AZ-1]
    set_fact:
      private_subnet_az1_id: "{{ my_private_subnet_az1.subnet.id }}"

# Creating Subnets in AZ-2

  - name:               Create Public Subnet [AZ-2]
    ec2_vpc_subnet:
      state:            "present"
      vpc_id:           "{{ vpc_id }}"
      cidr:             "10.0.11.0/24"
      az:               "{{ aws_region }}b"
      region:           "{{ aws_region }}"
      resource_tags:
        Name:           "AZ-2 Public Subnet 2"
    register: my_public_subnet_az2

  - name:               Set Public Subnet ID in variable [AZ-2]
    set_fact:
      public_subnet_az2_id: "{{ my_public_subnet_az2.subnet.id }}"

  - name:               Create Private Subnet [AZ-2]
    ec2_vpc_subnet:
      state:            "present"
      vpc_id:           "{{ vpc_id }}"
      cidr:             "10.0.12.0/24"
      az:               "{{ aws_region }}b"
      region:           "{{ aws_region }}"
      resource_tags:
        Name:           "AZ-2 Private Subnet 2"
    register: my_private_subnet_az2

  - name:               Set Private Subnet ID in variable [AZ-2]
    set_fact:
      private_subnet_az2_id: "{{ my_private_subnet_az2.subnet.id }}"


# Every VPC needs at least one Internet Gateway.
# This component allows traffic between the VPC and the outside world.
# Even though we have two AZ, we only need one Internet Gateway,
# as this component is external to our VPC, and highly available.

  - name:               Create Internet Gateway for VPC
    ec2_vpc_igw:
      vpc_id:           "{{ vpc_id }}"
      region:           "{{ aws_region }}"
      state:            "present"
      resource_tags:
        Name:           "Kunal IGW"
    register: my_vpc_igw

  - name:               Set Internet Gateway ID in variable
    set_fact:
      igw_id:           "{{ my_vpc_igw.gateway_id }}"

  - debug:
      msg: public subnet "{{  my_vpc_igw.gateway_id }}"
